services:
  predict:
    image: davalerova/predict:latest
    build: .
    ports:
      - "8008:80"
    env_file:
      - .env
    environment:
      - ROBOFLOW_API_KEY=${ROBOFLOW_API_KEY?Variable not set}
      - ROBOFLOW_PROJECT_NAME=${ROBOFLOW_PROJECT_NAME?Variable not set}
      - ROBOFLOW_PROJECT_VERSION=${ROBOFLOW_PROJECT_VERSION?Variable not set}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID?Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY?Variable not set}
      - AWS_REGION=${AWS_REGION?Variable not set}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME?Variable not set}
    volumes:
      - .:/code
